[package]
name = "egui-sdl3-platform"
version = "0.1.1"
edition = "2021"
authors = ["cohaereo <cohae@cohae.dev>"]
description = "SDL3 platform integration for egui"
homepage = "https://github.com/cohaereo/egui-sdl3-platform"
repository = "https://github.com/cohaereo/egui-sdl3-platform"
license = "MIT"
readme = "README.md"
categories = ["graphics", "game-development", "gui"]
keywords = ["egui", "sdl3", "sdl", "gui", "platform"]
include = ["**/*.rs", "Cargo.toml"]

[dependencies]
egui = "0.33.0"
log = "0.4.28"
sdl3 = { git = "https://github.com/serpilliere/sdl3-rs", branch="fix-keyup-modstate", features = ["raw-window-handle"]}

thiserror = "2.0.17"

[features]
sdl3-static = ["sdl3/build-from-source-static"]
default = []
